sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.2
  - ruby-head
branches:
  only:
    - source
cache:
  bundler: true
  directories:
    - vendor/bundle
    - $HOME/.rvm
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - travis_retry bundle update
  - bundle exec rake generate
notifications:
  email: false
